export const cinemaData: ICinema[] = [
  {
    id: '1',
    showTime: '12:30',
    hall: 'CineTech + hall 1',
    currency: '$',
    price: 50,
    bonus: 2500,
    seats: [
      [
        {id: '1-1', type: 'not-available' as SeatType},
        {id: '1-2', type: 'not-available' as SeatType},
        {id: '1-3', type: 'regular' as SeatType},
        {id: '1-4', type: 'regular' as SeatType},
        {id: '1-5', type: 'regular' as SeatType},
        {id: '1-6', type: 'regular' as SeatType},
        {id: '1-7', type: 'regular' as SeatType},
        {id: '1-8', type: 'regular' as SeatType},
        {id: '1-9', type: 'regular' as SeatType},
        {id: '1-10', type: 'regular' as SeatType},
        {id: '1-11', type: 'regular' as SeatType},
        {id: '1-12', type: 'not-available' as SeatType},
        {id: '1-13', type: 'not-available' as SeatType},
      ],
      [
        {id: '2-1', type: 'not-available' as SeatType},
        {id: '2-2', type: 'not-available' as SeatType},
        {id: '2-3', type: 'regular' as SeatType},
        {id: '2-4', type: 'regular' as SeatType},
        {id: '2-5', type: 'regular' as SeatType},
        {id: '2-6', type: 'regular' as SeatType},
        {id: '2-7', type: 'regular' as SeatType},
        {id: '2-8', type: 'regular' as SeatType},
        {id: '2-9', type: 'regular' as SeatType},
        {id: '2-10', type: 'regular' as SeatType},
        {id: '2-11', type: 'regular' as SeatType},
        {id: '2-12', type: 'not-available' as SeatType},
        {id: '2-13', type: 'not-available' as SeatType},
      ],
      [
        {id: '3-1', type: 'not-available' as SeatType},
        {id: '3-2', type: 'not-available' as SeatType},
        {id: '3-3', type: 'regular' as SeatType},
        {id: '3-4', type: 'regular' as SeatType},
        {id: '3-5', type: 'regular' as SeatType},
        {id: '3-6', type: 'regular' as SeatType},
        {id: '3-7', type: 'regular' as SeatType},
        {id: '3-8', type: 'regular' as SeatType},
        {id: '3-9', type: 'not-available' as SeatType}, // one gap
        {id: '3-10', type: 'regular' as SeatType},
        {id: '3-11', type: 'regular' as SeatType},
        {id: '3-12', type: 'regular' as SeatType},
        {id: '3-13', type: 'regular' as SeatType},
        {id: '3-14', type: 'regular' as SeatType},
        {id: '3-15', type: 'not-available' as SeatType},
        {id: '3-16', type: 'not-available' as SeatType},
      ],
      [
        {id: '4-1', type: 'not-available' as SeatType},
        {id: '4-2', type: 'not-available' as SeatType},
        {id: '4-3', type: 'regular' as SeatType},
        {id: '4-4', type: 'regular' as SeatType},
        {id: '4-5', type: 'regular' as SeatType},
        {id: '4-6', type: 'regular' as SeatType},
        {id: '4-7', type: 'regular' as SeatType},
        {id: '4-8', type: 'regular' as SeatType},
        {id: '4-9', type: 'regular' as SeatType},
        {id: '4-10', type: 'not-available' as SeatType}, // one gap
        {id: '4-11', type: 'regular' as SeatType},
        {id: '4-12', type: 'regular' as SeatType},
        {id: '4-13', type: 'regular' as SeatType},
        {id: '4-14', type: 'regular' as SeatType},
        {id: '3-15', type: 'not-available' as SeatType},
        {id: '3-16', type: 'not-available' as SeatType},
      ],
      // rows 5–9: all regular seats surrounded by edge not-available
      ...Array.from({length: 5}, (_, i) => {
        const row = i + 5;
        return [
          {id: `${row}-1`, type: 'not-available' as SeatType},
          {id: `${row}-2`, type: 'not-available' as SeatType},
          ...Array.from({length: 14}, (_, j) => ({
            id: `${row}-${j + 3}`,
            type: 'regular' as SeatType,
          })),
          {id: `${row}-17`, type: 'not-available' as SeatType},
          {id: `${row}-18`, type: 'not-available' as SeatType},
        ];
      }),
      // row 10: VIP seats
      [
        {id: '10-1', type: 'vip' as SeatType},
        {id: '10-2', type: 'vip' as SeatType},
        {id: '10-3', type: 'vip' as SeatType},
        {id: '10-4', type: 'vip' as SeatType},
        {id: '10-5', type: 'vip' as SeatType},
        {id: '10-6', type: 'vip' as SeatType},
        {id: '10-7', type: 'vip' as SeatType},
        {id: '10-8', type: 'vip' as SeatType},
        {id: '10-9', type: 'vip' as SeatType},
        {id: '10-10', type: 'vip' as SeatType},
        {id: '10-11', type: 'vip' as SeatType},
        {id: '10-12', type: 'vip' as SeatType},
        {id: '10-13', type: 'vip' as SeatType},
        {id: '10-14', type: 'vip' as SeatType},
        {id: '10-15', type: 'vip' as SeatType},
        {id: '10-16', type: 'vip' as SeatType},
        {id: '10-17', type: 'vip' as SeatType},
      ],
    ],
  },
  // You can copy the same seat layout for other showtimes or modify slightly if needed
  {
    id: '2',
    showTime: '15:30',
    hall: 'CineTech + hall 2',
    currency: '$',
    price: 75,
    bonus: 3000,
    seats: [
      [
        {id: '1-1', type: 'not-available' as SeatType},
        {id: '1-2', type: 'not-available' as SeatType},
        {id: '1-3', type: 'regular' as SeatType},
        {id: '1-4', type: 'regular' as SeatType},
        {id: '1-5', type: 'regular' as SeatType},
        {id: '1-6', type: 'regular' as SeatType},
        {id: '1-7', type: 'regular' as SeatType},
        {id: '1-8', type: 'regular' as SeatType},
        {id: '1-9', type: 'regular' as SeatType},
        {id: '1-10', type: 'regular' as SeatType},
        {id: '1-11', type: 'regular' as SeatType},
        {id: '1-12', type: 'not-available' as SeatType},
        {id: '1-13', type: 'not-available' as SeatType},
      ],
      [
        {id: '2-1', type: 'not-available' as SeatType},
        {id: '2-2', type: 'not-available' as SeatType},
        {id: '2-3', type: 'regular' as SeatType},
        {id: '2-4', type: 'regular' as SeatType},
        {id: '2-5', type: 'regular' as SeatType},
        {id: '2-6', type: 'regular' as SeatType},
        {id: '2-7', type: 'regular' as SeatType},
        {id: '2-8', type: 'regular' as SeatType},
        {id: '2-9', type: 'regular' as SeatType},
        {id: '2-10', type: 'regular' as SeatType},
        {id: '2-11', type: 'regular' as SeatType},
        {id: '2-12', type: 'not-available' as SeatType},
        {id: '2-13', type: 'not-available' as SeatType},
      ],
      [
        {id: '3-1', type: 'not-available' as SeatType},
        {id: '3-2', type: 'not-available' as SeatType},
        {id: '3-3', type: 'regular' as SeatType},
        {id: '3-4', type: 'regular' as SeatType},
        {id: '3-5', type: 'regular' as SeatType},
        {id: '3-6', type: 'regular' as SeatType},
        {id: '3-7', type: 'regular' as SeatType},
        {id: '3-8', type: 'regular' as SeatType},
        {id: '3-9', type: 'not-available' as SeatType}, // one gap
        {id: '3-10', type: 'regular' as SeatType},
        {id: '3-11', type: 'regular' as SeatType},
        {id: '3-12', type: 'regular' as SeatType},
        {id: '3-13', type: 'regular' as SeatType},
        {id: '3-14', type: 'regular' as SeatType},
        {id: '3-15', type: 'not-available' as SeatType},
        {id: '3-16', type: 'not-available' as SeatType},
      ],
      [
        {id: '4-1', type: 'not-available' as SeatType},
        {id: '4-2', type: 'not-available' as SeatType},
        {id: '4-3', type: 'regular' as SeatType},
        {id: '4-4', type: 'regular' as SeatType},
        {id: '4-5', type: 'regular' as SeatType},
        {id: '4-6', type: 'regular' as SeatType},
        {id: '4-7', type: 'regular' as SeatType},
        {id: '4-8', type: 'regular' as SeatType},
        {id: '4-9', type: 'regular' as SeatType},
        {id: '4-10', type: 'not-available' as SeatType}, // one gap
        {id: '4-11', type: 'regular' as SeatType},
        {id: '4-12', type: 'regular' as SeatType},
        {id: '4-13', type: 'regular' as SeatType},
        {id: '4-14', type: 'regular' as SeatType},
        {id: '3-15', type: 'not-available' as SeatType},
        {id: '3-16', type: 'not-available' as SeatType},
      ],
      // rows 5–9: all regular seats surrounded by edge not-available
      ...Array.from({length: 5}, (_, i) => {
        const row = i + 5;
        return [
          {id: `${row}-1`, type: 'not-available' as SeatType},
          {id: `${row}-2`, type: 'not-available' as SeatType},
          ...Array.from({length: 14}, (_, j) => ({
            id: `${row}-${j + 3}`,
            type: 'regular' as SeatType,
          })),
          {id: `${row}-17`, type: 'not-available' as SeatType},
          {id: `${row}-18`, type: 'not-available' as SeatType},
        ];
      }),
      // row 10: VIP seats
      [
        {id: '10-1', type: 'vip' as SeatType},
        {id: '10-2', type: 'vip' as SeatType},
        {id: '10-3', type: 'vip' as SeatType},
        {id: '10-4', type: 'vip' as SeatType},
        {id: '10-5', type: 'vip' as SeatType},
        {id: '10-6', type: 'vip' as SeatType},
        {id: '10-7', type: 'vip' as SeatType},
        {id: '10-8', type: 'vip' as SeatType},
        {id: '10-9', type: 'vip' as SeatType},
        {id: '10-10', type: 'vip' as SeatType},
        {id: '10-11', type: 'vip' as SeatType},
        {id: '10-12', type: 'vip' as SeatType},
        {id: '10-13', type: 'vip' as SeatType},
        {id: '10-14', type: 'vip' as SeatType},
        {id: '10-15', type: 'vip' as SeatType},
        {id: '10-16', type: 'vip' as SeatType},
        {id: '10-17', type: 'vip' as SeatType},
      ],
    ],
  },
  {
    id: '3',
    showTime: '18:30',
    hall: 'CineTech + hall 1',
    currency: '$',
    price: 75,
    bonus: 3000,
    seats: [
      [
        {id: '1-1', type: 'not-available' as SeatType},
        {id: '1-2', type: 'not-available' as SeatType},
        {id: '1-3', type: 'regular' as SeatType},
        {id: '1-4', type: 'regular' as SeatType},
        {id: '1-5', type: 'regular' as SeatType},
        {id: '1-6', type: 'regular' as SeatType},
        {id: '1-7', type: 'regular' as SeatType},
        {id: '1-8', type: 'regular' as SeatType},
        {id: '1-9', type: 'regular' as SeatType},
        {id: '1-10', type: 'regular' as SeatType},
        {id: '1-11', type: 'regular' as SeatType},
        {id: '1-12', type: 'not-available' as SeatType},
        {id: '1-13', type: 'not-available' as SeatType},
      ],
      [
        {id: '2-1', type: 'not-available' as SeatType},
        {id: '2-2', type: 'not-available' as SeatType},
        {id: '2-3', type: 'regular' as SeatType},
        {id: '2-4', type: 'regular' as SeatType},
        {id: '2-5', type: 'regular' as SeatType},
        {id: '2-6', type: 'regular' as SeatType},
        {id: '2-7', type: 'regular' as SeatType},
        {id: '2-8', type: 'regular' as SeatType},
        {id: '2-9', type: 'regular' as SeatType},
        {id: '2-10', type: 'regular' as SeatType},
        {id: '2-11', type: 'regular' as SeatType},
        {id: '2-12', type: 'not-available' as SeatType},
        {id: '2-13', type: 'not-available' as SeatType},
      ],
      [
        {id: '3-1', type: 'not-available' as SeatType},
        {id: '3-2', type: 'not-available' as SeatType},
        {id: '3-3', type: 'regular' as SeatType},
        {id: '3-4', type: 'regular' as SeatType},
        {id: '3-5', type: 'regular' as SeatType},
        {id: '3-6', type: 'regular' as SeatType},
        {id: '3-7', type: 'regular' as SeatType},
        {id: '3-8', type: 'regular' as SeatType},
        {id: '3-9', type: 'not-available' as SeatType}, // one gap
        {id: '3-10', type: 'regular' as SeatType},
        {id: '3-11', type: 'regular' as SeatType},
        {id: '3-12', type: 'regular' as SeatType},
        {id: '3-13', type: 'regular' as SeatType},
        {id: '3-14', type: 'regular' as SeatType},
        {id: '3-15', type: 'not-available' as SeatType},
        {id: '3-16', type: 'not-available' as SeatType},
      ],
      [
        {id: '4-1', type: 'not-available' as SeatType},
        {id: '4-2', type: 'not-available' as SeatType},
        {id: '4-3', type: 'regular' as SeatType},
        {id: '4-4', type: 'regular' as SeatType},
        {id: '4-5', type: 'regular' as SeatType},
        {id: '4-6', type: 'regular' as SeatType},
        {id: '4-7', type: 'regular' as SeatType},
        {id: '4-8', type: 'regular' as SeatType},
        {id: '4-9', type: 'regular' as SeatType},
        {id: '4-10', type: 'not-available' as SeatType}, // one gap
        {id: '4-11', type: 'regular' as SeatType},
        {id: '4-12', type: 'regular' as SeatType},
        {id: '4-13', type: 'regular' as SeatType},
        {id: '4-14', type: 'regular' as SeatType},
        {id: '3-15', type: 'not-available' as SeatType},
        {id: '3-16', type: 'not-available' as SeatType},
      ],
      // rows 5–9: all regular seats surrounded by edge not-available
      ...Array.from({length: 5}, (_, i) => {
        const row = i + 5;
        return [
          {id: `${row}-1`, type: 'not-available' as SeatType},
          {id: `${row}-2`, type: 'not-available' as SeatType},
          ...Array.from({length: 14}, (_, j) => ({
            id: `${row}-${j + 3}`,
            type: 'regular' as SeatType,
          })),
          {id: `${row}-17`, type: 'not-available' as SeatType},
          {id: `${row}-18`, type: 'not-available' as SeatType},
        ];
      }),
      // row 10: VIP seats
      [
        {id: '10-1', type: 'vip' as SeatType},
        {id: '10-2', type: 'vip' as SeatType},
        {id: '10-3', type: 'vip' as SeatType},
        {id: '10-4', type: 'vip' as SeatType},
        {id: '10-5', type: 'vip' as SeatType},
        {id: '10-6', type: 'vip' as SeatType},
        {id: '10-7', type: 'vip' as SeatType},
        {id: '10-8', type: 'vip' as SeatType},
        {id: '10-9', type: 'vip' as SeatType},
        {id: '10-10', type: 'vip' as SeatType},
        {id: '10-11', type: 'vip' as SeatType},
        {id: '10-12', type: 'vip' as SeatType},
        {id: '10-13', type: 'vip' as SeatType},
        {id: '10-14', type: 'vip' as SeatType},
        {id: '10-15', type: 'vip' as SeatType},
        {id: '10-16', type: 'vip' as SeatType},
        {id: '10-17', type: 'vip' as SeatType},
      ],
    ],
  },
];
